### ISSUE TITLE
Fix rspec deprecation warnings

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#453]
```
Deprecation Warnings:

Using `any_instance` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/christoph/Dropbox/git/vm-portal/spec/features/slack/slack_controller_spec.rb:49:in `block (2 levels) in <top (required)>'.

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/christoph/Dropbox/git/vm-portal/spec/controllers/dashboard_controller_spec.rb:55:in `block (4 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total
```

**Comment by chrisma** [comment]
https://stackoverflow.com/questions/24595203/rspec-any-instance-deprecation-how-to-fix-it

**Comment by chrisma** [comment]
Adressed in https://github.com/hpi-swt2/vm-portal/pull/454

**Comment by chrisma** [comment]
https://github.com/hpi-swt2/vm-portal/pull/454 is merged
